name: Generate ASSCI Artwork

on:
  push

jobs:
   ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: action/checkout@v4

    - name: install cowsay program
      run: sudo apt-get install cowsay -y 

    - name: execute cowsay cmd
      run: cowsay -f dragon "Run for Cover, I am a dragon....RAWR" >> dragon.txt

    - name: Test file exists 
      run: grep -i "dragon" dragon.txt

    - name: read file 
      run: cat dragon.txt

    - name: checkout repo files 
      run: ls -ltra



